server.port=8080
# ==================================================
# APPLICATION
# ==================================================
spring.application.name=api-gateway

# ==================================================
# JWT
# ==================================================
app.jwt.secret=${JWT_SECRET}

# ==================================================
# CORS
# ==================================================
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

# ==================================================
# ROUTES
# ==================================================
spring.cloud.gateway.server.webflux.routes[0].id=service-user-auth
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**, /api/seguridad/**

spring.cloud.gateway.server.webflux.routes[1].id=service-general
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/general/**

spring.cloud.gateway.server.webflux.routes[2].id=service-requerimiento
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/requerimiento/**

spring.cloud.gateway.server.webflux.routes[3].id=service-persona
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/persona/**

