spring.application.name=servicio-general
server.port=8082

spring.config.import=optional:classpath:application-db.properties
#spring.datasource.url=jdbc:sqlserver://webiisdes01:1433;databaseName=GestionRQ;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================





