# ==========================================
# CONEXION DB
# ==========================================

spring.datasource.url=${DB_URL:jdbc:sqlserver://webiisdes01:1433;databaseName=GestionRQ;integratedSecurity=true;encrypt=true;trustServerCertificate=true;}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false

# ==========================================
# JSON CONFIGURATION
# ==========================================
spring.jackson.default-property-inclusion=non_null

# ==========================================
# JWT CONFIGURATION
# ==========================================
# Si JWT_SECRET no esta definida en el sistema, usa la clave por defecto tras los dos puntos:
app.jwt.secret=${JWT_SECRET:6UsqmF9oAlmne2Bv4LgR6OwDlFjQVUpKFhLE8hcOqOs=}

app.jwt.expiration=600000
# 600000 ms = 10 minutos

# ==========================================
# ERROR HANDLING
# ==========================================
spring.web.error.include-message=always